#!/bin/bash

#outputFiles=$(ls *.out|sort -V)
outputFiles=$@

for file in $outputFiles
do

    energy=$(grep "FINAL SINGLE POINT ENERGY" $file | tail -1 | awk '{print $5}')
    echo $file $energy

done

