#!/usr/bin/env python3

import argparse
import shutil
import os
import re

parser = argparse.ArgumentParser()
parser.add_argument('files', nargs='+', help='files to open')
args = parser.parse_args()

OUTPUT_DIRECTORY = "/tmp/tmp.gaussview"

try:
    shutil.rmtree(OUTPUT_DIRECTORY)
    os.mkdir(OUTPUT_DIRECTORY)
except FileNotFoundError:
    os.mkdir(OUTPUT_DIRECTORY)

def identify_file_format(file):
    regex_g16 = r'This is part of the Gaussian\(R\) 16 program\.'
    regex_orca5 = r'\* O   R   C   A \*'
    regex_xyz = r'(^ +)?([a-zA-Z]{1,2})([\s\t]+(-?[0-9]+\.[0-9]+))([\s\t]+(-?[0-9]+\.[0-9]+))([\s\t]+(-?[0-9]+\.[0-9]+))'

    with open(file) as f:
        file_content = f.readlines()

    if len(file_content) < 20:
        file_head = file_content[:3]
    else:
        file_head = file_content[:20]

    for line in file_head:
        if re.search(regex_g16,line):
            file_format='g16'
            break
        elif re.search(regex_orca5,line):
            file_format='orca'
            break
        elif re.search(regex_xyz,line):
            file_format='xyz'
            break
        else:
            file_format = None
            continue
    
    return file_format

for filepath in args.files:
    format = identify_file_format(filepath)

    basename = os.path.basename(filepath)
    _ = basename.rsplit('.', 1)
    filename = _[0]
    extension = _[1]

    shutil.copy(filepath, OUTPUT_DIRECTORY)
    if format == 'g16':
        pass
    elif format == 'orca':
        os.system(f'OfakeG {OUTPUT_DIRECTORY}/{basename} > /dev/null 2>&1')
        shutil.move(f"{OUTPUT_DIRECTORY}/{filename}_fake.{extension}", f"{OUTPUT_DIRECTORY}/{basename}")
    elif format == 'xyz':
        os.system(f'obabel -ixyz {OUTPUT_DIRECTORY}/{basename} -omol > {OUTPUT_DIRECTORY}/{filename}.mol 2> /dev/null')
        os.remove(f"{OUTPUT_DIRECTORY}/{basename}")
    else:
        print("Unrecognized format. Exiting...")
        exit()
        
os.system(f'gv {OUTPUT_DIRECTORY}/* &')