[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chemtools"
version = "0.1"
description = "Your chemistry toolbox"
dependencies = []  # Add any package dependencies here
