#!/bin/bash

xyzCoordinates=$@

for xyzCoordinate in $xyzCoordinates
do
    inputFile=${xyzCoordinate%.*}.inp

    echo '! pal4' > $inputFile
   # echo '! B3LYP NumFreq PrintBasis Def2-SV(P) CPCM(water)' >> $inputFile
    echo '! r2scan-3c' >> $inputFile 
    echo ''  >> $inputFile
   
   # echo '%output print[p_MOs] 1 end' >> $inputFile
   # echo '' >> $inputFile    

   # echo '%tddft' >> $inputFile
   # echo 'nroots 10' >> $inputFile
   # echo 'maxdim 30' >> $inputFile
   # echo 'end' >> $inputFile
   # echo '' >> $inputFile

   # echo '%plots Format Cube' >> $inputFile
   # echo '    dim1 100' >> $inputFile
   # echo '    dim2 100' >> $inputFile
   # echo '    dim3 100' >> $inputFile  
   # for i in 47 48 49 50
   # do
   #     echo "    MO(\"${xyzCoordinate%.*}_orbital-$i.cube\",$i,0);" >> $inputFile
   # done
   # echo 'end' >> $inputFile
   # echo '' >> $inputFile

   # echo '%base "scr"'  >> $inputFile
    echo '* xyz 0 1'  >> $inputFile
    cat $xyzCoordinate | sed '1,2 d' >> $inputFile 
    echo '*'  >> $inputFile

done
