#!/bin/bash

files=$@

for file in $files
do
	file_basename=${file%.*}

	echo "# irc=(calcfc, maxcycles=1000, maxpoints=1000, stepsize=25, recorrect=never) external='xtb-gaussian --gfn 1'" > $file_basename.com
	echo "" >> $file_basename.com
	echo $file_basename >> $file_basename.com
	echo "" >> $file_basename.com
	echo "0 1" >> $file_basename.com
	tail -n +3 $file >> $file_basename.com
	echo "" >> $file_basename.com
	echo "" >> $file_basename.com
done
